server:
  port: 8001

spring:
  profiles:
    active: dev
  # 应用名称
  application:
    name: user

# eureka配置
eureka:
  # eureka客户端配置
  client:
    # 指定服务注册中心的位置
    service-url:
      defaultZone: http://localhost:8000/eureka

